### ISSUE TITLE
界面的建议

### ISSUE THREAD

**Issue by RayPragma** [heterophyllus/Geopter#1]
Quadoa了解一下

**Comment by heterophyllus** [comment]
Sorry, I can't speak Chinese.
Could you rewrite the comment (and issue title) in English?

**Comment by RayPragma** [comment]
A software of Opitcal designing which is named Quadoa, have many good concept in UI for our optical design.

**Comment by heterophyllus** [comment]
Thank you for reply.

This time I got to know Quadoa and it looked interesting.
Though, It provides least information for the moment, so we can only wait for its official release.

I wish it would offer free-trial version to even private users.

**Comment by RayPragma** [comment]
https://drive.google.com/file/d/1hItQXEFh5nYWO_SHkpHxflLMcO2pPzSw/view?usp=sharing

**Comment by RayPragma** [comment]
Why you delete this

**Comment by heterophyllus** [comment]
Sorry, I should have left a comment.
That was because I didn't think you have the right to redistribute it.

**Comment by RayPragma** [comment]
This is a trial version with limit function. An agent gave it to me, and gave me permission to give it to someone else.

**Comment by heterophyllus** [comment]
If that was true, I might have misunderstood.

Nevertheless, I'm still hesitant to use or redistribute such proprietary software (even trial versions) without direct confirmation from the developer or its official dealer.

I'm responsible for my own repository and I want to avoid it becoming a suspicious redistributer.

I would appreciate if you could accept my personal policy.
