### ISSUE TITLE
CMake Error at geopter/gui/CMakeLists.txt:60 (add_executable)

### ISSUE THREAD

**Issue by xt9527514048** [heterophyllus/Geopter#2]
## Details of Improvement
Dear Author:
thanks a lot for your great efforts.I can run the release version Geopter-0.2.0,but when compile the source codes. The Qt returns :
CMake Error at geopter/gui/CMakeLists.txt:60 (add_executable):
  Target "Geopter" links to target "Qt::Widgets" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
I try to solve the problem by adding 
set(CMAKE_PREFIX_PATH "D:/Qt/6.1.3/msvc2019_64/lib/cmake")   as you suggested
but it fails to work in my computer.

I'm wondering how to fix this problem. 

## Environment
Windows 10 Qt 6.1.3

**Comment by heterophyllus** [comment]
Thank you for trying my application.

I'm afraid you use Qt6 instead of Qt5.
Some of the lines in CMakeLists.txt explicitly specify Qt5, so one possible solution for the error is to edit them to be compatible with Qt6.
Of course we have another way; install Qt5 in your computer.

**Comment by xt9527514048** [comment]
Dear Hiiragi:
        Thanks very much for your kind reply.  I modified the CMakeLists and replace Qt5 with Qt6,but some of fuctions and structure changed in Qt6 .So I annotated some error codes. And finally it can be runned but the layout fuction is not work because the codes was annnotated . 
      I will try to use Qt5 to solve the problem finally. And I will try to add some optimization codes to your application.  Thanks very much for your great work!

**Comment by xt9527514048** [comment]
Dear  Hiiragi:

I use Qt5 to run the codes, and still get the same problem, the cmake can not find the Qt5::Widgets. And I replace the codes

in CMakeList in  ~\Geopter-master\geopter\gui

"target_link_libraries(Geopter PRIVATE Qt${QT_VERSION_MAJOR}::Widgets Qt${QT_VERSION_MAJOR}::PrintSupport QCustomPlot)"

with "target_link_libraries(Geopter PRIVATE Qt5::Widgets Qt5::PrintSupport QCustomPlot) "

and finally fixed the problem.

 

 

And in ~\Geopter-master\geopter\optical\src\Sequential\sequential_path.cpp

SequentialPathComponent SequentialPath::at(int i) const

{

assert(i>=0);

 

in order to use assert  I add #include<cassert> in the front


and fixed the compiling error

Thanks for your nice application again !



Yours ，           Teng Xu
