### ISSUE TITLE
Question: how is the implementation validated?

### ISSUE THREAD

**Issue by dibyendumajumdar** [heterophyllus/Geopter#3]
Hi @heterophyllus  

Thank you for this great project - is it still based on MJH Ray optics? 

How do you validate the implementation in terms of correctness? I am curious as I find this is the difficult part.

Regards

**Comment by heterophyllus** [comment]
Hi @dibyendumajumdar 

Yes, it is still based on mjhoptics/ray-optics, though I have modified a lot.

Your question is critical.  I'm struggling how to validate it, too.
For the moment,  I'm just comparing the result with the parent project mjhoptics/ray-optics, which is the most realistic way.
I know it's not enough, but I'm feeling helpless against my poor options.

**Comment by dibyendumajumdar** [comment]
Yes I face this issue as well - I struggle to match results from one implementation to another - and not having access to something like OSLO makes it harder to validate
