### ISSUE TITLE
Qt environment in Windows10 

### ISSUE THREAD

**Issue by jenarlion** [heterophyllus/Geopter#4]
Sorry to disturb you，my dear friend heterophyllus.
I had a question which this program could not run on Windows 10 x64.
It was shown followed steps：
1. First，I downloaded the exe program from release in your project.
2. Then， I installed the vc_redist.x64.exe.
3. Last， I run it with double clicked geopter-gui.exe.
At the end， it could not run after "double click".
So， I hope I have the honour to know whether I didnot install any other programs of Qt environment in Windows10. If it was true，please tell me to find and install them，thanks.
your friend fromChina

**Comment by heterophyllus** [comment]
Thank you for the feedback.

I recently recieved a similar inquiry saying nothing happens in double-clicking geopter-gui.exe.  So, I assume your problem is the same one.

I regret that I have not yet found out how to fix it.
As you guess, it is one of the  possible solutions to set up the same environment as mine by installing Qt and related dependencies.  However, it should not be the best way and a more fundamental solution is needed.

Now I'm still struggling with the problem.
I apologize to be helpless with you.

**Comment by heterophyllus** [comment]
I would like to inform this problem has been successfully resolved and the modified zip package has been uploaded to release page.
(file: Geopter_v0-5-1_modified_16-July-2022.zip)

It was confirmed to work well in several different Windows systems without installing Qt and other libraries.
I would appreciate if you check whether it works on your own environment.

**Comment by jenarlion** [comment]
Ah，well！
Thank you for your response and help，it can run very well.
&nbsp;Thank you for your good spirit of sharing and providing such a good tool. 

I wish you a happy work and all the best. 



From your friend of China




叶贸中
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "heterophyllus/Geopter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月17日(星期天) 上午7:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [heterophyllus/Geopter] Qt environment in Windows10  (Issue #4)





 
I would like to inform this problem has been successfully resolved and the modified zip package has been uploaded to release page.
 (file: Geopter_v0-5-1_modified_16-July-2022.zip)
 
It was confirmed to work well in several different Windows systems without installing Qt and other libraries.
 I would appreciate if you check whether it works on your own environment.
