### ISSUE TITLE
reference book

### ISSUE THREAD

**Issue by zxuanyu** [heterophyllus/Geopter#5]
hello！Excuse me, what reference book did you use?
Thank you for your reply！

**Comment by heterophyllus** [comment]
Sorry for my late reply.
In coding this software, the following materials were referred to implement the theoretical aspects.

- Michael Bass, et al: Handbook of Optics, McGraw-Hill
- Herbert Gross: Handbook of Optical Systems, Wiley
- Rudolf Kingslake: Lens Design Fundamentals, SPIE
- Jose Sasian: Introduction to Aberrations in Optical Imaging Systems, Cambridge University Press
- Benjamin I. Amador: Computational Fourier Optics a MATLAB tutorial, SPIE
- Zemax Optic Studio Manual
...etc
